### ISSUE TITLE
Error message when gh-board does not exist is confusing

### ISSUE THREAD

**Issue by jayvdb** [coala/community#185]
See https://gitter.im/coala/community?at=5b7baa45d8d36815e56a0c8a

**Comment by ishucr7** [comment]
Hi @jayvdb . I looked into the issue and noticed that the error is due to the code in the [file](https://github.com/coala/community/blob/master/data/management/commands/fetch_deployed_data.py) 
.It tries to fetch the file from first the deployed_url , if we don't have gh-board deployed, then it tries to fetch from upstream_deployed url. 
But here we don't have the condition where we handle the case when the file doesn't exist on upstream_deployed url.
I intend to add an exception there handling that case.
Shall I go with this approach? Let me know what you think.
Thanks.

**Comment by jayvdb** [comment]
But the file always exists on coala's gh-board , so it should fail on direct forks of the coala's org repo.

**Comment by li-boxuan** [comment]
@ishucr7 The logic you may want to change is this function: https://github.com/coala/community/blob/master/community/git.py#L179

The file does exist on upstream org, but in a different repo. Check out this function https://github.com/coala/community/blob/master/community/git.py#L158 where we can specify the repo. Maybe you want to do something similar with `get_upstream_deploy_url`

**Comment by ishucr7** [comment]
Oh I see. I tried as you said by passing the repo's name as an argument and it worked. I'll add the PR soon.
